export default {
	values: Object.freeze({
		TEXT: Symbol(Number(1)),
		NUMBER: Symbol(2),
		EMAIL: Symbol(3),
		PASSWORD: Symbol(4),
		TEXTAREA: Symbol(5),
		DATE: Symbol(6),
		TIME: Symbol(7),
		SELECT: Symbol(8),
		CHECKLIST: Symbol(9),
		SWITCH: Symbol(10),
		EDITOR: Symbol(11),
		TITLE: Symbol(12),
		FILEPCKR: Symbol(13),
		PARAGRAPH: Symbol(14),
		ILLUSTRATION: Symbol(15),
		PHONE: Symbol(16),
	}),
	labels: {
		1: "texte",
		2: "nombre",
		3: "email",
		4: "mot de passe",
		5: "zone texte",
		6: "date",
		7: "temps",
		8: "liste déroulante",
		9: "liste à coche",
		10: "bouton bascule",
		11: "éditeur",
		12: "titre",
		13: "fichier(s)",
		14: "paragraphe",
		15: "illustration",
		16: "téléphone",
	},
};
