export default {
	values: Object.freeze({
		USER_FIRSTNAME: Symbol("user.firstname"),
		USER_LASTNAME: Symbol("user.lastname"),
		USER_EMAIL: Symbol("user.email"),
		USER_PHONE: Symbol("user.phone"),
		ADDRESS_STREET_ADDRESS: Symbol("address.street_address"),
		ADDRESS_CITY: Symbol("address.city"),
		ADDRESS_POSTAL_CODE: Symbol("address.postal_code"),
		ADDRESS_COUNTRY: Symbol("address.country"),
		ADDRESS_ORGANIZATION: Symbol("address.organization"),
		ADDRESS_VAT_NUMBER: Symbol("address.vat_number"),
		COMPANION_ADDRESS_STREET_ADDRESS: Symbol("companion.address.street_address"),
		COMPANION_ADDRESS_CITY: Symbol("companion.address.city"),
		COMPANION_ADDRESS_POSTAL_CODE: Symbol("companion.address.postal_code"),
		COMPANION_ADDRESS_COUNTRY: Symbol("companion.address.country"),
		COMPANION_ADDRESS_ORGANIZATION: Symbol("companion.address.organization"),
		COMPANION_ADDRESS_VAT_NUMBER: Symbol("companion.address.vat_number"),
		FORM_RESPONSE_WITH_NEWSLETTER: Symbol("form_response.with_newsletter"),
	}),
	labels: {
		"user.firstname": "Prénom",
		"user.lastname": "Nom",
		"user.email": "Email",
		"user.phone": "Téléphone",
		"address.street_address": "Facturation - Rue",
		"address.city": "Facturation - Ville",
		"address.postal_code": "Facturation - Code postal",
		"address.country": "Facturation - Pays",
		"address.organization": "Facturation - Société",
		"address.vat_number": "Facturation - Numéro de TVA",
		"companion.address.street_address": "Accompagnant - Facturation - Rue",
		"companion.address.city": "Accompagnant - Facturation - Ville",
		"companion.address.postal_code": "Accompagnant - Facturation - Code postal",
		"companion.address.country": "Accompagnant - Facturation - Pays",
		"companion.address.organization": "Accompagnant - Facturation - Société",
		"companion.address.vat_number": "Accompagnant - Facturation - Numéro de TVA",
		"form_response.with_newsletter": "Avec newsletter",
	},
};
